### ISSUE TITLE
Does not Parse Textarea HTML Elements Correctly

### ISSUE THREAD

**Issue by MrHamel** [Kekos/multipart-form-data-parser#2]
This does not parse <textarea> HTML elements correctly.

**Comment by Kekos** [comment]
Could you please provide an example HTTP request that this library fails to parse? Or maybe a file with HTML and PHP to reproduce the problem?

**Comment by MrHamel** [comment]
Unfortunately, I cannot provide the PHP files as it's used in an OpenSwoole web application. As for the HTML, just create an HTML form and fill the text area with paragraphs of lorem ipsum.

The issue was it cutoff everything after the first line.

Ryan
________________________________

**Comment by Kekos** [comment]
I found the problem now, please try version 1.1.2
